# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_Fit_win.ui'
#
# Created: Fri Jun  8 19:24:51 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1288, 644)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1140, 578, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(30, 60, 1221, 501))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1219, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 576, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox.setGeometry(QtCore.QRect(88, 575, 62, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMaximum(2.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setProperty("value", 1.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(160, 580, 81, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pB_reload = QtWidgets.QPushButton(Dialog)
        self.pB_reload.setGeometry(QtCore.QRect(1167, 20, 81, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pB_reload.setFont(font)
        self.pB_reload.setObjectName("pB_reload")
        self.pB_savecondtion = QtWidgets.QPushButton(Dialog)
        self.pB_savecondtion.setGeometry(QtCore.QRect(990, 20, 161, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pB_savecondtion.setFont(font)
        self.pB_savecondtion.setObjectName("pB_savecondtion")
        self.cB_use_anotherParams = QtWidgets.QCheckBox(Dialog)
        self.cB_use_anotherParams.setGeometry(QtCore.QRect(30, 23, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.cB_use_anotherParams.setFont(font)
        self.cB_use_anotherParams.setObjectName("cB_use_anotherParams")
        self.lE_params = QtWidgets.QLineEdit(Dialog)
        self.lE_params.setEnabled(False)
        self.lE_params.setGeometry(QtCore.QRect(230, 20, 731, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.lE_params.setFont(font)
        self.lE_params.setObjectName("lE_params")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Dialog", "Close", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "S02:", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("Dialog", "fit S02", None, -1))
        self.pB_reload.setText(QtWidgets.QApplication.translate("Dialog", "Reload", None, -1))
        self.pB_savecondtion.setText(QtWidgets.QApplication.translate("Dialog", "Save conditions", None, -1))
        self.cB_use_anotherParams.setText(QtWidgets.QApplication.translate("Dialog", "Use another parameters", None, -1))
        self.lE_params.setToolTip(QtWidgets.QApplication.translate("Dialog", "<html><head/><body><p>Write another parameters for fitting.</p><p>Ex. parameter name: dR, initial value: 0.05, status[guess or set]: guess</p><p>=&gt; \'dR\': [0.05, \'guess\'] (use quotation mark for strings. Separate each parameters with \';\')</p></body></html>", None, -1))

